name: Release Alpha and Propose Stable

on:
  pull_request:
    types: [closed]
    branches: [dev]
  workflow_dispatch:

jobs:
  publish_alpha:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets: inherit
    with:
      branch: 'dev'
      version_file: 'ovos_translate_server_plugin/version.py'
      update_changelog: true
      publish_prerelease: true
      changelog_max_issues: 100
